#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306
#    username: root
#    password: cbf26266
##  jpa:
##    hibernate.ddl-auto: update
##    generate-ddl: true
##    show-sql: true
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://38.109.217.119/inu?serverTimezone=UTC
    username: daasXXX
    password: 111111
    initialization-mode: always
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
spring.servlet.multipart:
  max-file-size: 128KB
  max-request-size: 128KB